### PR TITLE
Add Carthage support

### PR DESCRIPTION
**Pull request by ewerx**
- Share scheme to enable Carthage builds.
- Remove extra files from build target to fix command-line build errors.

TODO:
- tag latest release (Carthage only picks up tagged releases)

### CODE REVIEW

**Comment by bitwit** [comment]
Thanks for the contribution. I've just been having some issues getting the release tagged and ready for Cocoapods since they released cocoapods v1.0 but as soon as I work that stuff out I'll merge this in too and make sure the release is properly tagged

**Comment by bitwit** [comment]
@ewerx I'm new to carthage, do I need to publish anything else? Version 2.0.0 has just been published and tagged on git.

**Comment by ewerx** [comment]
You will need another release tag that includes this PR. All carthage does is check out the latest tag and build the framework via xcodebuild. This PR just exposes the scheme for command-line build, so you just need a new tagged release after merging this and it should work.

**Comment by bitwit** [comment]
@ewerx this is now published and tagged. Thanks for the contrib. Please let me know if there are any issues

**Pull request merged**
